version: '3'

  
services:
     mything:
      build: ./nginx/  
      container_name: nginx-container  
      ports:  
       - 80:80
       - 443:443  
      links:  
       - php  
      volumes:
       - ./www/html/:/var/www/html/  

     php:    
      build: ./php/  
      container_name: php-container  
      expose:  
       - 9000  
      links:  
       - mysql  
      volumes:  
       - ./www/html/:/var/www/html/

     mysql:    
      image: mysql:5.7  
      container_name: mysql-container  
      volumes:
        - /var/lib/mysql
      environment:  
       MYSQL_ROOT_PASSWORD: secret  
       MYSQL_DATABASE: mydb  
       MYSQL_USER: myuser  
       MYSQL_PASSWORD: password

     redis-server:
      restart: always
      image: redis:4.0
      container_name: redis-server
      command: /bin/bash -c 'redis-server --appendonly yes'
      sysctls:
         - net.core.somaxconn=65535
      ports:
         - "6380:6379"
      volumes:
         - ./redis:/data
