global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['3.110.221.105:9090'] ## IP Address of the localhost. Match the port to your container port
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['3.110.221.105:9100'] ## IP Address of the localhost
  - job_name: 'docker-metrics'
    static_configs:
      - targets: ['3.110.221.105:9323']
  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['3.110.221.105:8080']

